### ISSUE TITLE
Politics - Ideologies

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#12]
Outdated, please see the post below

**Political Parties**

- Communist
- Market Socialist
- Democratic Socialist
- Progressive
- Centrist
- Liberal
- Conservative
- Traditionalist
- Reactionary Populist
- Fascist

**IG & Characters Ideologies**

**Political Ideologies**
_Government Type Views_
- Republican
- Monarchist
- Theocratic Revolutionary
- Socialist Revolutionary
- Militarist Revolutionary

_Government Power Views_
- Dictatorial
- Authoritarian
- Democratic
- Anarchist

_Cultural Tolerance_
- Racial Supremacist
- Racial Pluralist

_Religious Tolerance_
- Religious Supremacist
- Racial Pluralist

_Religious Views_
- Moralist
- Secularist
- Atheist

_General Societal Rights Views_
- Progressive Activist
- Conservative Activist

_Colonial Views_
- Colonialist
- De-Colonist
- Anti-Colonialist

_War Views_
- Expansionist
- Defensive
- Pacifist

_Military Views_
- Militarist
- Anti-Militarist

_Conscription Views_
- Pro-Conscription
- Anti-Conscription

_WMD Views_
- Pro WMD
- Anti WMD

_Foreign Integration Views_
- Globalist
- Pan-Nationalist (ie. Regionalist)
- Nationalist

**Economic Ideologies**

_Economic System Views_
- Fully Planned
- Semi Planned
- State Capitalism
- Interventionism
- Laissez-faire

_Employee Rights Views_
- Pro Workers
- Pro Capitalists

_Foreign Economic Integration Views_
- Free Trade Advocate
- Trade Protectionist

**Comment by ccfox** [comment]
A few suggestions, maybe:

'Democratic Socialism' into something to represent actual socialist ideologies and then something to encompass Social Democratic parties that wouldn't fit into progressive or liberal - but would obviously not be radical enough to label as socialist (i.e. the modern Social Democratic parties of Europe). Socialist could be for things like more radical social democrats that still adhere to socialist economic policies (in the timeline of the mod off the top of my head that would be the Independent Labour Party, PSOE, Socialist Party USA, etc).

Adding something akin to 'Promotion of Dominant Culture' and/or 'Minority Oppression' to the Racial tolerance category for regimes that were harsh against minorities without being racial supremacists.

What is the difference between 'Anti-Militarist' and 'Pacifist'?

I'd add 'Compulsory Military Service' and 'Civilian Service' for conscription, to represent nations that require all citizens to serve in the military for a set length of time and the ones that offer different non-military jobs as an alternative to doing so.

Depending on what 'Globalist' there means, I'd add 'Internationalist' and/or 'Alter-Globalist'. I'd also leave Pan-Nationalist in with nationalist and rename it to 'Regionalist' for nations that are more focused on region.

**Comment by settintotrieste** [comment]
New ideology system:

Ideologies will be divided up into 4 groups: Concentration of Power, State vs Individual rights, economic tilt and foreign affairs tilt

**Concentration of power**
[Character ideology only] 
This group determines distribution of power & centralisation
- Autocratic
- Elitist (Supports biased voting)
- Democratic (Supports fair voting)

[Optional]
This group determines cultural rights
- Cultural Supremacist
- Nationalist
- Multiculturalist

[Optional]
This group determines religious rights
- Moralist
- Secularist
- Atheism

[Optional]
This group determines Gender Rights
- Patriarchal
- Egalitarian 

** State vs Individuals right**
This group determine support for human rights (except cultural and religious rights)
- Communitarian
- Centrist
- Individualist

** Economic Tilt **
This group determines support for internal economic laws and policies
- Planned Economist
- State Capitalist
- Keynesian
- Market Interventionist
- Free Marketeer

This group determines the trade policy
- Exporter
- Importer
- Free Trader

[Optional]
This group determines the specialisation of the economy
- Agrarianism
- Industrialist
- Corporatist [Service industry]

** Foreign Affairs Tilt **
This determines Foreign Policy
- Globalist
- Regionalist 
- Nationalist

This determines War Policy
- Jingoist
- Interventionist
- Anti-War
