### ISSUE TITLE
how to contribute to mod dev?

### ISSUE THREAD

**Issue by p-drolima** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#20]
Hi mate,

Interested in contributing to the mod dev but I have never modded before so kind of looking for some guidance. I love the potential of this mod and would like to contribute somehow. interested?

**Comment by p-drolima** [comment]
my stack spectrum is wide ranging from backend to frontend...

**Comment by settintotrieste** [comment]
Hi, thank you. You’re welcome to help. Please let me know what you like to do for the mod.
