### ISSUE TITLE
Gov - Institutions

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#3]
**Political Institutions**
- Head of State's Office (5)
- Federal Administration Services (5)
- Elections Watchdog (5)
- Civil Service (5)
- Judiciary (5)
- Diplomatic Corps (5)
- Superstate Institutions (5)

**Citizen's Institutions**
- Paramilitary Organisation (5)
- Propaganda Ministry (5)
- Law Enforcement (5)
- Secret Police (5)
- National Trade Union (5)
- State Ombudsman (5)
- Concentration Camp Network (5)

**Economic Institutions**
- Health Ministry (5)
- Education Ministry (5)
- Unemployment Office (5)
- Pensions Office (5)
- Public Housing Board (5)
- Financial Regulator (5)
- Trade Board (5)
- Economic Development Board (5) / State Planning Committee (5)
- National Space Agency (5)

**Military Institutions**
- Army (5)
- Airforce (5)
- Navy (5)
- Nuclear Weapons (5)
- Chemical Weapons (5)
- Biological Weapons (5)
- Space Force (5)
- Military Intelligence (5)
- Conscription Office (5)
- Republican Guard (5) / Royal Guard (5) / The Red Guard (5) / Revolutionary Guard Corps (5)

**Comment by settintotrieste** [comment]
I think the current one fine. Secret Police represents domestic intelligence while military intelligence is foreign intelligence. I didn’t want to give both an intelligence name because not all secret police were known as intelligence services.

**Comment by danclave** [comment]
As far as I can tell, not a direct copy. But something similar to capacities or a currency could be made using variables and very cleanly inserted into the GUI.

**Comment by goodboyclek** [comment]
It is better to make concentration camps not an institute, but buildings. For example, it reduces the percentage of radicals, but increases the percentage depending on the law of dependents (in prison) or deaths (executions). Or it increases the percentage of deaths of non-titular nationality. This will give players the flexibility they need to clear or suppress certain regions, especially newly captured ones.

**Comment by settintotrieste** [comment]
This is a good idea

**Comment by xxxAnn** [comment]
"Federal administrative services" is not a great name: not all countries are federations.
