### ISSUE TITLE
Countries leave trade unions, and unable to join trade unions

### ISSUE THREAD

**Issue by KosayJabre** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#47]
After a bit ingame, all countries seem to split up and form their own trade unions (eg. Australia no longer in British trade union). No amount of positive relation fixes it, it becomes impossible to rejoin

**Comment by settintotrieste** [comment]
Hi, I ran some tests over the week using the beta and 1.5 public versions but I wasn’t able to replicate the issue mentioned. One thing you need to know is that customs unions are decoupled from some puppet status so, for example, a dominion does not create a CU with its overlord unless there’s simultaneously a CU pact. So what could have happened is that the UK or France or some large CU leader entered into a CU with USA or some other country and that terminated all CU pacts that they had with their dominions or other countries. This outcome is not a bug as the CU diplo pact needs to terminate in such a case to prevent a crash from a customs Union between 2 junior partners.
