### ISSUE TITLE
About the National People's Assembly in PRC

### ISSUE THREAD

**Issue by lomirus** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#48]
Hello, I am translating this mod into Simplified Chinese, and in the process of translation, I noticed the term "National People's Assembly" when selecting the PRC. However, I cannot find a corresponding institution in PRC, and I cannot find any related information on Google. Can you provide any information about this so I can translate this term?

**Comment by settintotrieste** [comment]
Hi, ‘National People’s Assembly’ is a generic name for communist countries with no specially defined parliament name. I’m not familiar with the PRC state structure but If there’s an equivalent institution I can add a custom entry for their parliament so it shows a unique name and not the default generic one.

**Comment by lomirus** [comment]
Some related institutions:

- National People's Congress(NPC): The People's Republic of China adopts the system of unity of the legislature and the executive, and the legal status of the people's congresses is higher than that of the executive and judicial organs. The National People's Congress exercises the following powers: to amend the Constitution; to supervise the implementation of the Constitution; to legislate; to make appointments and removals; to decide on important matters; and to supervise.
- Standing Committee of the NPC: When the National People's Congress is not in session, the Standing Committee of the NPC, which is a standing legislative body, exercises most of its powers and functions on its behalf. The Standing Committee of the National People's Congress exercises head-of-state authority jointly with the President of the State.
- National Committee of the Chinese People's Political Consultative Conference(NCCPPCC): The Chinese People's Political Consultative Conference(CPPCC) and its Standing Committee are second only to the Central Committee of the CCP, the Standing Committee of the NPC, and the State Council in the domestic arena, and they also play a role in communicating with leaders of political parties and people from all walks of life in foreign countries. However, it is not part of the national institutional system and is not a legislative body, can only participate in the discussion of the country's major political policies and make suggestions and criticisms.
- Standing Committee of the NCCPPCC: Like the Standing Committee of the NPC, when the NCCPPCC is not in session, the Standing Committee of the NCCPPCC, which is elected by the NCCPPCC, exercises most of its powers and functions on behalf of the NCCPPCC.

As the NPC and the CPPCC are the main deliberative bodies of China, they are often referred to as the Two Sessions. However, the National People's Congress, like the Supreme Soviet of the former Soviet Union, is the highest deliberative body, while the CPPCC is a body for consulting on state policy between the CCP, democratic parties and other social organizations, but is not a parliament and does not have the power to legislate, create or review laws. The NPC and CPPCC are collectively known as the "two chambers", but they are not bicameral. Only the National People's Congress is the highest legislative and power organ.

**Comment by settintotrieste** [comment]
Added changes in ec6394d

**Comment by lomirus** [comment]
About the Executive Body, maybe State Council would be more appropriate? (Sorry forgot to mention)

> The State Council of the People's Republic of China, also known as the Central People's Government, is the chief administrative authority and the national cabinet of China. It is constitutionally the highest administrative organ of the country and the executive organ of the National People's Congress, the highest organ of state power. It is composed of the premier, vice premiers, state councilors, ministers of ministries, directors of committees, the auditor general, and the secretary-general.
>
> The State Council is described by the Chinese constitution as the executive organ of the National People's Congress (NPC), as well as the "highest state administrative organ".

See [State Council of the People's Republic of China - Wikipedia](https://en.wikipedia.org/wiki/State_Council_of_the_People%27s_Republic_of_China)

**Comment by settintotrieste** [comment]
Alright and no worries. I'll do it this way then:

Bicameral Legislature Law: 
- Upper House: Chinese People's Political Consultative Conference [CPPCC is elevated to an official legislative body]
- Lower House: National People's Congress

Hybrid Legislature Law: [PRC's starting law]
- Executive Body: State Council
- Parliament: National People's Congress

Unicameral Legislature
- Parliament: National People's Congress
