### ISSUE TITLE
International - Ranks

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#5]
**UN Recognised**
Superpower
Great Power
Major Power
Minor Nation
Insignificant State

**UN Unrecognised**
Unrecognised Major Power
Unrecognised Minor Power
Unrecognised State

[*If THIS does not have the UNGA modifier then it will be Unrecognised no matter what; joining the UNGA will be via decision]

**Country Tiers**
V3 tiers to be renamed to something more appropriate so no Kingdom tier for FGR, as an example.

**Comment by danclave** [comment]
Alternative suggestion for UN Recognised:

Superpower
Global Power
Regional Power
Minor Nation
Insignificant State

**Comment by settintotrieste** [comment]
I prefer to avoid references to regional or global powers because I don’t want to make it look like countries are limited to where they can declare an interest. The ranks should stick to determining interest capacity rather than where interests are actually exercised. It can also give the player more flexibility to play as a non interventionist Superpower like what the UK did during the 1800s and also represent things like Sweden getting involved in Kurdish affairs despite Turkey being in a different region and Sweden being only a Minor Power.

The ‘other interest’ capability should be like this:
Superpower - No limit to how many interests can be declared
Great Power - 7 interests limit
Major Power - 3 Interests limit
Minor Nation - 1 interest limit
Insignificant State - 0 interest
*All ranks will have V3’s default auto interest in own region.
