### ISSUE TITLE
More correct census data for Italy and surrounding areas

### ISSUE THREAD

**Issue by Zzyxas** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#77]
So, since I am a bad player that most commonly plays one country, I've taken a stab at better census data for Italy and the surrounding data I most commonly blob- err, interact with.
Most data has been scaled down from 1951-1954 census data to 1950 at a 1% per year reduction; I tried my best to track down various minorities data, with only a scant approximate guesses; most Jewish minorities are gone, as have Austrians in Istria and a fair number of Italians in Dalmatia (just a rough estimate). but I did add in the Arbereshe and Griko (ethnic Albanians and Greeks) of Southern Italy.

States I've touched up:
Savoy and Corsica (resized from 1954 French census, removed the Italians from Savoy), Malta (used the actual 1951 data)
All Italian states (taken from 1951 census), with minorities data taken from various sites that track minority records, adjusted as best possible as some in-game states comprise multiple _Regioni_ or even parts of _Province_.
Istria: Italian census for the Italian part (which is smaller, the 1946 census, adjusted for four years' growth, for the Yugoslav area (with a downward adjustment of Italians to account for the then-ongoing emigration of ethnic Italians); the 1946 Allies Command estimate for the TLT area.
Dalmatia: I just removed 20k Italians, leaving only roughly 24k in there, adding 20k Croats as a stopgap measure as I could not find

Sources:
https://ebiblio.istat.it/digibib/Sommario%20Statistiche%20Storiche/BVE0011281Sommario_storico_statistiche_popolazione_1951_1987.pdf
https://en.wikipedia.org/wiki/The_Holocaust_in_Italy
https://web.archive.org/web/20221019063846/https://www.ethnologue.com/language/frp
https://fr.wikipedia.org/wiki/D%C3%A9mographie_de_la_Corse
https://en.wikipedia.org/wiki/Demographics_of_Malta
https://it.m.wikipedia.org/wiki/File:Italian_regions_provinces.svg
https://it.wikipedia.org/wiki/Demografia_di_San_Marino
https://worldpopulationreview.com/countries/vatican-city-population
https://it.wikipedia.org/wiki/Sloveni_in_Italia
https://www.istrianet.org/istria/demography/giuricin_riflessioni-cadastre1945.htm
https://it.wikipedia.org/wiki/Provincia_autonoma_di_Bolzano
https://it.wikipedia.org/wiki/Arb%C3%ABresh%C3%AB#Distribuzione_geografica

Files I've updated:
[00_west_europe.txt](https://github.com/user-attachments/files/16489159/00_west_europe.txt)
[01_south_europe.txt](https://github.com/user-attachments/files/16489160/01_south_europe.txt)

**Comment by Zzyxas** [comment]
It seems that by taking away the double pops in Yugoslavian Istria, the TRE pops are not correctly initialised. So there's that to be fixed, I suppose (everything else works).

**Comment by settintotrieste** [comment]
Thanks for the updated demographics, will add this for the next steam update.
