### ISSUE TITLE
Update to various European/North African POPs

### ISSUE THREAD

**Issue by Zzyxas** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#78]
A list of the changes made:

- made the French pops in Piedmont Occitan, a better fit
- removed the small Italian pop in Provence
- changed the Italian Albanians from Sunni to Catholic
- adjusted Libyan pops, using 1950 total pop estimate as the basis, and the trended share of the three states (1939 vs 1964 vs 2012 census)
- adjusted Swiss pops according to 1950 census data: https://www.bfs.admin.ch/bfs/en/home/statistics/catalogues-databases/publications/overviews/statistical-yearbook-switzerland.assetdetail.346171.html
- overhauled pops in French Tunisia according to: https://fr.wikipedia.org/wiki/Histoire_des_Juifs_en_Tunisie / https://fr.wikipedia.org/wiki/Protectorat_fran%C3%A7ais_de_Tunisie#D%C3%A9mographie
- overhauled Yugoslavian POPs: https://en.wikipedia.org/wiki/Demographics_of_the_Socialist_Federal_Republic_of_Yugoslavia
- corrected Greek and Bulgarian POPs: https://en.wikipedia.org/wiki/Demographics_of_Bulgaria / https://en.wikipedia.org/wiki/Demographics_of_Greece
- adjusted Romanian POPs: https://en.wikipedia.org/wiki/Hungarians_in_Romania / https://en.wikipedia.org/wiki/Demographics_of_Romania
- overhauled Egyptian POPs through extrapolation of the 1947-1970 census data: https://etheses.dur.ac.uk/7971/1/7971_4969-vol1.PDF

[00_west_europe.txt](https://github.com/user-attachments/files/17002429/00_west_europe.txt)
[01_south_europe.txt](https://github.com/user-attachments/files/17002430/01_south_europe.txt)
[02_east_europe.txt](https://github.com/user-attachments/files/17002431/02_east_europe.txt)
[03_north_africa.txt](https://github.com/user-attachments/files/17002432/03_north_africa.txt)

**Comment by settintotrieste** [comment]
Thanks for the changes!
