### ISSUE TITLE
International - Diplomatic Actions

### ISSUE THREAD

**Issue by settintotrieste** [settintotrieste/Victoria-3-Cold-War-Era-Mod-CWE#8]
These are Diplomatic Actions additional to what V3 already has

**Ongoing**
_Nuclear Weapons Related_
- Station Nuclear Weapons in Country
- Extend Nuclear Umbrella to Country

_Espionage Related_
- Send Spies
- Support Opposition Party [Increases Turmoil, decreases relations over time]
- Support Secession Movements [Increases Turmoil, decreases relations over time]

_Sanctions_
- Impose Diplomatic Sanctions [Increase diplo capacity costs]
- Impose Economic Sanctions [Increase cost of consumer goods etc]
- Impose Military Sanctions [Increase cost of military goods etc]
- Cut Off All Ties [THIS cancels all agreements with and cannot enter into any new agreements with FROM]

_Sending Advisors_
- Provide Economic Assistance
- Provide Political Assistance
- Provide Military Assistance

_Tech & Goods Transfers_
- Arms Agreement
- Research Agreement [Operates on top of normal tech diffusion so it would have a hidden yearly pulse event which gives a random tech that the technologically superior party has to the technologically inferior party.]
- Trade Agreement [Joining the WTO creates a TA with all WTO members]

_Military Diplo Pacts_
- Full Alliance [From V3]
- Defensive Alliance [From V3]
- Non-Aggression Pact [THIS ends all alliances with and cannot enter into any new alliance with countries hostile with FROM]
- Special Relationship [THIS and FROM will always get involved in each other's diplomatic plays on the same side]
- Guarantee Independence [Creates Protectorate Subject Relationship]

_Economic Diplo Pacts_
- Monetary Union
- Customs Union
- Provide Financial Assistance [edited Bankroll X; IMF loans, Marshall Plan etc will create this between creditor and lender]

**Instant**
_Military Actions_
- Surprise Attack [Attacker's war aim is always the Unconditional Surrender CB]
- Conduct Military Strike [State target]
- Conduct Chemical Weapons Strike [State target]
- Conduct Biological Weapons Strike [State target]
- Conduct Tactical Nuclear Weapons Strike [State target]
- Issue Nuclear Ultimatum [Country target; full scale nuclear strike]
Retaliation behaviour will be through event so once a DA to strike X is issued, the other side will get an event to strike back.
If target is under a nuclear umbrella then that country will get an event to retaliate.

_Espionage Actions_
- Conduct Domestic Provocation [State target; Increases Turmoil in state]
- Conduct Economic Attack [State target; Imposes economic malus modifier]
- Conduct Cyberattack [Country target; Increases Turmoil slightly & imposes economic malus modifier]
- Assassinate Exiled Dissidents (Adds authority to THIS, greatly reduce relations with FROM)
- Conduct Border Provocation [State target, only states bordering this or a sea state; Reduces relations]

_Hostile Diplomatic Actions_
- Seize Country's Assets (Massively reduces relations + gain money but voids all trade agreements)
- Arrest Nationals (Moderately reduces relations)
- Kill Nationals (Creates a Diplomatic Incident for reparations)
- Expel Diplomats (Moderately reduces relations)
- Attack Embassy (Massively reduces relations)

_Friendly Diplomatic Actions_
- Offer Obligation [ie. a bribe to greatly increase relations]

_International Blocs_
- Request Ideological Bloc Membership (Democratic, Communist Blocs) [From leader of bloc]
- Request Military Bloc Membership (NATO, Warsaw Pact etc) [From leader of bloc]
- Request Superstate/Economic Bloc Membership (EU, ASEAN, etc) [From leader of bloc, ie Customs Union Leader]

**Comment by danclave** [comment]
Suggesting "Send Advisors" as an ongoing diplomatic action. With larger, modern powers sending advisors to help modernize a country and increase their own influence. Examples are USSR advisors in China and US advisors in South Vietnam.

**Comment by settintotrieste** [comment]
Thanks. That is a good suggestion. I've divided up the sending of advisors into diplo, economic and military so there can be more flexibility as to where to help the country.

**Comment by danclave** [comment]
If you want to tie it into the tech system, maybe the 3 types of advisors would reflect the 3 types of technology. Economic, Military and cultural advisors.

**Comment by settintotrieste** [comment]
Yeah that’s a possibility though I wouldn’t use ‘cultural advisors’ as the name for the DA.

**Comment by settintotrieste** [comment]
Yeah. I guess advisors can also provide buffs for things other than techs. So for example economic gives slight boosts to trade and factories, military boosts mil stats and political increases admin capacity and authority.

I think expel advisors might be superfluous as it can be represented as just terminating the send advisors DA. Request might lead to spamming of requests from AI countries so it might not be good to add.

**Comment by danclave** [comment]
Regarding request advisors, we could forbid the AI from using them and make them rely on the "send advisors" DA done by other countries, but leave the "Request Advisor" option open for players so that don't have to wait for the AI to act in order to get advisors and can clearly see all the conditions they need to fulfil to be able to receive advisors.

**Comment by settintotrieste** [comment]
I think it’s better not to have separate DAs for AI and players. All options should be available to both the AI and player to use as far as possible.
